### ISSUE TITLE
Vox meme for social media images

### ISSUE THREAD

**Issue by mebates** [cfpb/hackathon#25]
We could turn our documentary photography into social graphics, using Vox Media's meme generator. Would be super sweet if we could figure out how to add a beam or creatively incorporate CFPB's logo, rather than a watermark. 

https://github.com/voxmedia/meme

Who's with me !?

**Comment by Scotchester** [comment]
Documentary photography?

This is definitely interesting to me. I can't Ruby, but would love to pitch in on the front end.

**Comment by mebates** [comment]
Anything from https://www.flickr.com/photos/cfpbphotos/

**Comment by contolini** [comment]
If this will be a public project, you'll want to limit which images can be uploaded (perhaps by using flickr's API to pull from that album). Otherwise, you risk letting people watermark inappropriate photos with our logo.

@Scotchester I think we could pretty easily remove the Ruby requirement and serve it from gh-pages. All the image processing is done in the browser and I think they're just using Ruby to serve assets and build the project. I recently built a similar tool: https://github.com/yes-lab/mobile-meme-generator/

**Comment by cfarm** [comment]
This sounds really fun.

**Comment by mebates** [comment]
Is there anything I should do to help prep for this project?

**Comment by ascott1** [comment]
I'd say either be there to provide design support or draft up some really specific guidelines about what this should do. Obvious preference would be @mebates real life participation at the hackathon.

Anything else @cfarm?

**Comment by mebates** [comment]
Definitely planning on real life participation, all day!
